# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95e7a4b31925e3c748a8f179bb03fdfe4d4f214581a7b60500beb0697e3afd046121e65f27e834eb44d0dea68bcf550c2ae2df06d5b8cd1f11cf6001000675ff

test:
  secret_key_base: 0ebcdd85d648b003ef931ebd265ef7de106599f53f51e4d8e13c84466e4df5c77a76d4d252555612963e051b234ccc22f203eee344d71d18737bb70997611a87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
